export type HashtagSet = {
  id: number;
  category: 'ai-image' | 'ai-video' | 'creator' | 'business' | 'festival' | 'education';
  titleTa: string;
  titleEn: string;
  descriptionTa: string;
  descriptionEn: string;
  factTa: string;
  factEn: string;
  bestFor: string[];
  tags: string[];
};

export const hashtagSets: HashtagSet[] = [
  {
    id: 1,
    category: 'ai-image',
    titleTa: '80s AI Photo Trend',
    titleEn: '80s AI photo trend',
    descriptionTa: 'Retro Tamil studio portrait, DP edits, couple photo recreations.',
    descriptionEn: 'Retro Tamil studio portraits, DP edits, and couple photo recreations.',
    factTa: 'Hashtags reach-ஐ மட்டும் push செய்யாது; caption-ல் “80s Tamil photo prompt” போன்ற keywords சேர்ப்பது முக்கியம்.',
    factEn: 'Hashtags alone do not push reach; add keywords like “80s Tamil photo prompt” inside the caption.',
    bestFor: ['Instagram', 'TikTok', 'YouTube Shorts'],
    tags: ['80sPhotoTrend', 'TamilAI', 'AIPhotoEditing', 'RetroPortrait', 'TamilReels'],
  },
  {
    id: 2,
    category: 'ai-image',
    titleTa: 'AI Saree Portrait',
    titleEn: 'AI saree portrait',
    descriptionTa: 'Saree transformation, studio portrait, traditional creator posts.',
    descriptionEn: 'Saree transformations, studio portraits, and traditional creator posts.',
    factTa: 'Niche tag + style tag + community tag சேர்த்தால் algorithm-க்கு content context தெளிவாக கிடைக்கும்.',
    factEn: 'A niche tag, style tag, and community tag give the algorithm clearer content context.',
    bestFor: ['Instagram', 'Pinterest', 'TikTok'],
    tags: ['AISaree', 'SareePortrait', 'TamilAI', 'AIPhotoEditing', 'TraditionalLook'],
  },
  {
    id: 3,
    category: 'ai-image',
    titleTa: 'Tamil Wedding AI',
    titleEn: 'Tamil wedding AI',
    descriptionTa: 'Couple portraits, wedding studio concepts, invitation moodboards.',
    descriptionEn: 'Couple portraits, wedding studio concepts, and invitation moodboards.',
    factTa: 'Wedding content seasonal search பெறும்; location/style words caption-ல் இருந்தால் discoverability மேம்படும்.',
    factEn: 'Wedding content gets seasonal search demand; location and style words in captions improve discovery.',
    bestFor: ['Instagram', 'Pinterest', 'Facebook'],
    tags: ['TamilWedding', 'WeddingAI', 'CouplePortrait', 'WeddingReels', 'AIPhotoPrompt'],
  },
  {
    id: 4,
    category: 'ai-video',
    titleTa: 'Kling AI Video',
    titleEn: 'Kling AI video',
    descriptionTa: 'Image-to-video, cinematic motion, AI video experiments.',
    descriptionEn: 'Image-to-video, cinematic motion, and AI video experiments.',
    factTa: 'Video hashtags-ல் tool name + format + niche சேர்த்தால் search intent நல்லா match ஆகும்.',
    factEn: 'For video hashtags, combine the tool name, format, and niche to match search intent.',
    bestFor: ['TikTok', 'Instagram Reels', 'YouTube Shorts'],
    tags: ['KlingAI', 'AIVideo', 'ImageToVideo', 'TamilReels', 'AIVideoPrompt'],
  },
  {
    id: 5,
    category: 'ai-image',
    titleTa: 'Midjourney Poster',
    titleEn: 'Midjourney poster',
    descriptionTa: 'Poster concepts, cinematic art, Tamil creator design inspiration.',
    descriptionEn: 'Poster concepts, cinematic art, and Tamil creator design inspiration.',
    factTa: 'Copyright-safe captions முக்கியம்: celebrity/movie names இல்லாமல் style intent மட்டும் குறிப்பிடவும்.',
    factEn: 'Copyright-safe captions matter: describe the style intent without celebrity or movie names.',
    bestFor: ['Instagram', 'Pinterest', 'X'],
    tags: ['MidjourneyPrompt', 'AIPoster', 'TamilDesign', 'CinematicArt', 'AIArtPrompt'],
  },
  {
    id: 6,
    category: 'ai-image',
    titleTa: 'Gemini AI Image',
    titleEn: 'Gemini AI image',
    descriptionTa: 'Photo edits, prompt tests, Tamil AI tutorials.',
    descriptionEn: 'Photo edits, prompt tests, and Tamil AI tutorials.',
    factTa: 'Tool-specific hashtag tutorials-க்கு நல்லது; ஆனால் caption-ல் actual use case தெளிவாக எழுத வேண்டும்.',
    factEn: 'Tool-specific hashtags help tutorials, but the caption still needs the actual use case.',
    bestFor: ['Instagram', 'TikTok', 'YouTube Shorts'],
    tags: ['GeminiAI', 'GeminiPrompt', 'AIImagePrompt', 'TamilAI', 'PhotoEditing'],
  },
  {
    id: 7,
    category: 'ai-video',
    titleTa: 'Chennai Night Reel',
    titleEn: 'Chennai night reel',
    descriptionTa: 'Rainy street video, bike reel, cinematic city edits.',
    descriptionEn: 'Rainy street videos, bike reels, and cinematic city edits.',
    factTa: 'Local tags Chennai/Tamil Nadu audience-ஐ signal செய்யும்; broad tags மட்டும் போதாது.',
    factEn: 'Local tags signal the Chennai/Tamil Nadu audience; broad tags alone are not enough.',
    bestFor: ['Instagram Reels', 'TikTok', 'YouTube Shorts'],
    tags: ['ChennaiReels', 'TamilNadu', 'CinematicReel', 'AIVideo', 'NightRide'],
  },
  {
    id: 8,
    category: 'business',
    titleTa: 'Filter Coffee Ad',
    titleEn: 'Filter coffee ad',
    descriptionTa: 'Cafe, restaurant, food brand, South Indian product ads.',
    descriptionEn: 'Cafe, restaurant, food brand, and South Indian product ads.',
    factTa: 'Food posts-க்கு product keyword + local identity சேர்த்தால் saves/shares அதிகரிக்க வாய்ப்பு.',
    factEn: 'Food posts can earn more saves and shares when product keywords meet local identity.',
    bestFor: ['Instagram', 'Facebook', 'Pinterest'],
    tags: ['FilterCoffee', 'SouthIndianFood', 'TamilBusiness', 'FoodReels', 'CafeMarketing'],
  },
  {
    id: 9,
    category: 'business',
    titleTa: 'Local Shop Marketing',
    titleEn: 'Local shop marketing',
    descriptionTa: 'Tamil small business offers, product posts, WhatsApp campaigns.',
    descriptionEn: 'Tamil small business offers, product posts, and WhatsApp campaigns.',
    factTa: 'Local business hashtag-ஐ offer/city keyword உடன் இணைத்தால் வாங்கும் intent மேம்படும்.',
    factEn: 'Pair local business hashtags with offer and city keywords to improve buyer intent.',
    bestFor: ['Instagram', 'Facebook', 'WhatsApp Status'],
    tags: ['TamilBusiness', 'LocalShop', 'SmallBusinessIndia', 'ShopLocal', 'InstagramMarketing'],
  },
  {
    id: 10,
    category: 'creator',
    titleTa: 'Tamil Instagram Caption',
    titleEn: 'Tamil Instagram caption',
    descriptionTa: 'Creator captions, relatable Tamil posts, daily reels.',
    descriptionEn: 'Creator captions, relatable Tamil posts, and daily reels.',
    factTa: 'Caption hook first 125 characters-ல் strong ஆக இருந்தால் viewers “more” click செய்ய வாய்ப்பு அதிகம்.',
    factEn: 'A strong hook in the first 125 characters improves the chance that viewers tap “more.”',
    bestFor: ['Instagram', 'Threads', 'Facebook'],
    tags: ['TamilCaption', 'TamilCreator', 'TamilReels', 'ContentCreator', 'SocialMediaTips'],
  },
  {
    id: 11,
    category: 'creator',
    titleTa: 'YouTube Shorts Tamil',
    titleEn: 'YouTube Shorts Tamil',
    descriptionTa: 'Shorts hooks, faceless videos, Tamil voiceover clips.',
    descriptionEn: 'Shorts hooks, faceless videos, and Tamil voiceover clips.',
    factTa: 'YouTube-ல் title, thumbnail, description hashtags-ஐ விட முக்கியம்; hashtags context signal மட்டுமே.',
    factEn: 'On YouTube, title, thumbnail, and description matter more than hashtags; tags mainly add context.',
    bestFor: ['YouTube Shorts', 'Instagram Reels', 'TikTok'],
    tags: ['TamilShorts', 'YouTubeShorts', 'TamilReels', 'ShortsCreator', 'VideoScript'],
  },
  {
    id: 12,
    category: 'festival',
    titleTa: 'Pongal Greeting',
    titleEn: 'Pongal greeting',
    descriptionTa: 'Festival posts, brand greetings, family/community visuals.',
    descriptionEn: 'Festival posts, brand greetings, and family/community visuals.',
    factTa: 'Festival tags time-sensitive; festival-க்கு 2–3 வாரங்களுக்கு முன்பே post செய்தால் search window கிடைக்கும்.',
    factEn: 'Festival tags are time-sensitive; post 2–3 weeks before the festival to catch the search window.',
    bestFor: ['Instagram', 'Facebook', 'WhatsApp Status'],
    tags: ['Pongal', 'PongalWishes', 'TamilFestival', 'FestivalGreeting', 'TamilBusiness'],
  },
  {
    id: 13,
    category: 'festival',
    titleTa: 'Diwali Tamil Post',
    titleEn: 'Diwali Tamil post',
    descriptionTa: 'Diwali greetings, shop offers, festive creative ideas.',
    descriptionEn: 'Diwali greetings, shop offers, and festive creative ideas.',
    factTa: 'Festival offer posts-ல் one offer + one CTA + few hashtags வைத்தால் spam போல தெரியாது.',
    factEn: 'Festival offer posts look cleaner with one offer, one CTA, and a few hashtags.',
    bestFor: ['Instagram', 'Facebook', 'Pinterest'],
    tags: ['DiwaliWishes', 'TamilFestival', 'FestiveOffer', 'FestivalPost', 'DiwaliDesign'],
  },
  {
    id: 14,
    category: 'festival',
    titleTa: 'Tamil New Year',
    titleEn: 'Tamil New Year',
    descriptionTa: 'Puthandu wishes, brand greetings, family posts.',
    descriptionEn: 'Puthandu wishes, brand greetings, and family posts.',
    factTa: 'Tamil + English spelling variations சேர்ப்பது misspelling/search variation capture செய்ய உதவும்.',
    factEn: 'Tamil and English spelling variations help capture search variation and misspellings.',
    bestFor: ['Instagram', 'Facebook', 'YouTube Shorts'],
    tags: ['TamilNewYear', 'Puthandu', 'TamilFestival', 'NewYearWishes', 'TamilCulture'],
  },
  {
    id: 15,
    category: 'ai-image',
    titleTa: 'Professional Headshot',
    titleEn: 'Professional headshot',
    descriptionTa: 'LinkedIn profile, resume, founder photo transformations.',
    descriptionEn: 'LinkedIn profile, resume, and founder photo transformations.',
    factTa: 'Professional content-ல் broad viral hashtags விட intent tags நம்பகமாக இருக்கும்.',
    factEn: 'For professional content, intent tags are more credible than broad viral hashtags.',
    bestFor: ['LinkedIn', 'Instagram', 'X'],
    tags: ['ProfessionalHeadshot', 'LinkedInPhoto', 'AIPhotoEdit', 'FounderBrand', 'PersonalBranding'],
  },
  {
    id: 16,
    category: 'ai-image',
    titleTa: 'Product Photography',
    titleEn: 'Product photography',
    descriptionTa: 'Ecommerce, catalog, product ad and listing visuals.',
    descriptionEn: 'Ecommerce, catalog, product ad, and listing visuals.',
    factTa: 'Product hashtags-ல் category + use case சேர்த்தால் shoppers/content creators இருவரையும் reach செய்யலாம்.',
    factEn: 'Product hashtags with category plus use case can reach shoppers and creators.',
    bestFor: ['Instagram', 'Pinterest', 'Facebook'],
    tags: ['ProductPhotography', 'AIProductPhoto', 'EcommerceIndia', 'ProductAd', 'SmallBusiness'],
  },
  {
    id: 17,
    category: 'ai-video',
    titleTa: 'Product Reveal Video',
    titleEn: 'Product reveal video',
    descriptionTa: 'Reels product launch, packaging reveal, ad storyboard.',
    descriptionEn: 'Reels product launches, packaging reveals, and ad storyboards.',
    factTa: 'Reveal videos-க்கு hook caption + relevant 5 tags combo better than generic viral tags.',
    factEn: 'Reveal videos perform cleaner with a hook caption plus five relevant tags, not generic viral tags.',
    bestFor: ['Instagram Reels', 'TikTok', 'YouTube Shorts'],
    tags: ['ProductReveal', 'AIVideo', 'ProductLaunch', 'ReelsIdeas', 'BrandVideo'],
  },
  {
    id: 18,
    category: 'ai-video',
    titleTa: 'Travel Reel Tamil Nadu',
    titleEn: 'Tamil Nadu travel reel',
    descriptionTa: 'Temple, beach, market, food and travel content.',
    descriptionEn: 'Temple, beach, market, food, and travel content.',
    factTa: 'Travel content-ல் place tags மிகவும் முக்கியம்; generic #travel மட்டும் போதாது.',
    factEn: 'Place tags are important for travel content; generic #travel alone is too broad.',
    bestFor: ['Instagram Reels', 'YouTube Shorts', 'TikTok'],
    tags: ['TamilNaduTravel', 'ChennaiDiaries', 'TempleTravel', 'TravelReels', 'SouthIndia'],
  },
  {
    id: 19,
    category: 'ai-video',
    titleTa: 'Food Making Reel',
    titleEn: 'Food making reel',
    descriptionTa: 'Restaurant kitchens, home chefs, recipe shorts.',
    descriptionEn: 'Restaurant kitchens, home chefs, and recipe shorts.',
    factTa: 'Food reels saves பெற அதிக வாய்ப்பு; recipe/dish keyword caption-ல் கண்டிப்பாக சேர்க்கவும்.',
    factEn: 'Food reels often earn saves; include the recipe or dish keyword in the caption.',
    bestFor: ['Instagram Reels', 'YouTube Shorts', 'TikTok'],
    tags: ['FoodReels', 'TamilFood', 'RecipeShorts', 'HomeChef', 'SouthIndianFood'],
  },
  {
    id: 20,
    category: 'ai-video',
    titleTa: 'Photo To Motion',
    titleEn: 'Photo to motion',
    descriptionTa: 'Portrait animation, image-to-video, subtle motion reels.',
    descriptionEn: 'Portrait animation, image-to-video, and subtle motion reels.',
    factTa: 'Image-to-video trend-ல் before/after words caption-ல் இருந்தால் watch time curiosity அதிகரிக்கும்.',
    factEn: 'For image-to-video trends, “before/after” wording in the caption can increase curiosity.',
    bestFor: ['TikTok', 'Instagram Reels', 'YouTube Shorts'],
    tags: ['PhotoToVideo', 'ImageToVideo', 'AIVideo', 'PortraitAnimation', 'TamilAI'],
  },
  {
    id: 21,
    category: 'creator',
    titleTa: 'Faceless Reels',
    titleEn: 'Faceless reels',
    descriptionTa: 'Creators who post without showing face.',
    descriptionEn: 'Creators who post without showing their face.',
    factTa: 'Faceless niche-ல் topic clarity முக்கியம்; hashtags creator type-ஐ மட்டும் சொல்லக்கூடாது.',
    factEn: 'In faceless niches, topic clarity matters; hashtags should not only describe the creator type.',
    bestFor: ['Instagram Reels', 'TikTok', 'YouTube Shorts'],
    tags: ['FacelessReels', 'TamilCreator', 'ReelsIdeas', 'ContentIdeas', 'CreatorTips'],
  },
  {
    id: 22,
    category: 'creator',
    titleTa: 'Podcast Clip',
    titleEn: 'Podcast clip',
    descriptionTa: 'Tamil podcast snippets, opinion clips, interview moments.',
    descriptionEn: 'Tamil podcast snippets, opinion clips, and interview moments.',
    factTa: 'Podcast clips-ல் topic tag + guest/industry keyword caption-ல் இருந்தால் context தெளிவாகும்.',
    factEn: 'Podcast clips need the topic tag plus guest or industry keywords in the caption for context.',
    bestFor: ['Instagram Reels', 'YouTube Shorts', 'LinkedIn'],
    tags: ['TamilPodcast', 'PodcastClips', 'InterviewClip', 'TamilContent', 'CreatorEconomy'],
  },
  {
    id: 23,
    category: 'business',
    titleTa: 'WhatsApp Offer',
    titleEn: 'WhatsApp offer',
    descriptionTa: 'Local offers that can be reused as Instagram/Facebook posts.',
    descriptionEn: 'Local offers that can be reused as Instagram or Facebook posts.',
    factTa: 'WhatsApp-ல் hashtags முக்கியமில்லை; ஆனால் same content Instagram/Facebook-ல் post செய்ய இந்த set useful.',
    factEn: 'Hashtags do not matter much on WhatsApp, but this set helps when republishing to Instagram/Facebook.',
    bestFor: ['Instagram', 'Facebook', 'WhatsApp Status'],
    tags: ['OfferAlert', 'TamilBusiness', 'LocalDeals', 'ShopLocal', 'LimitedOffer'],
  },
  {
    id: 24,
    category: 'business',
    titleTa: 'Real Estate Walkthrough',
    titleEn: 'Real estate walkthrough',
    descriptionTa: 'Flat, villa, rental property and broker reels.',
    descriptionEn: 'Flat, villa, rental property, and broker reels.',
    factTa: 'Real estate-ல் city/locality keywords caption-ல் இல்லாமல் hashtags மட்டும் போதாது.',
    factEn: 'Real estate posts need city/locality keywords in the caption; hashtags alone are not enough.',
    bestFor: ['Instagram Reels', 'Facebook', 'YouTube Shorts'],
    tags: ['RealEstateIndia', 'PropertyTour', 'HouseTour', 'TamilNaduHomes', 'ApartmentTour'],
  },
  {
    id: 25,
    category: 'ai-image',
    titleTa: 'Anime Tamil Avatar',
    titleEn: 'Anime Tamil avatar',
    descriptionTa: 'DP, stickers, anime-style identity posts.',
    descriptionEn: 'DPs, stickers, and anime-style identity posts.',
    factTa: 'Stylized avatar posts shareable; community + style tags சேர்க்கவும்.',
    factEn: 'Stylized avatar posts are shareable; combine community and style tags.',
    bestFor: ['Instagram', 'TikTok', 'Pinterest'],
    tags: ['AnimeAvatar', 'TamilAnime', 'AIAvatar', 'ProfilePicture', 'DigitalArt'],
  },
  {
    id: 26,
    category: 'ai-image',
    titleTa: 'Black & White Editorial',
    titleEn: 'Black and white editorial',
    descriptionTa: 'Actor profile, moody portrait, magazine-style posts.',
    descriptionEn: 'Actor profiles, moody portraits, and magazine-style posts.',
    factTa: 'Mood/style tags portfolio discovery-க்கு உதவும்; caption-ல் “black and white editorial portrait” போன்ற phrase சேர்க்கவும்.',
    factEn: 'Mood and style tags help portfolio discovery; add phrases like “black and white editorial portrait.”',
    bestFor: ['Instagram', 'LinkedIn', 'Pinterest'],
    tags: ['EditorialPortrait', 'BlackAndWhitePhoto', 'PortraitMood', 'AIPhotoEdit', 'CreativePortrait'],
  },
  {
    id: 27,
    category: 'education',
    titleTa: 'AI Tips Tamil',
    titleEn: 'AI tips Tamil',
    descriptionTa: 'Prompt tips, AI tutorial posts, beginner education.',
    descriptionEn: 'Prompt tips, AI tutorial posts, and beginner education.',
    factTa: 'Educational posts save/share பெறும்; “how to” keywords caption-ல் எழுதுவது hashtag-ஐ விட பலமாக இருக்கும்.',
    factEn: 'Educational posts earn saves and shares; “how to” keywords in captions are stronger than hashtags alone.',
    bestFor: ['Instagram', 'LinkedIn', 'YouTube Shorts'],
    tags: ['AITipsTamil', 'PromptTips', 'TamilAI', 'LearnAI', 'CreatorEducation'],
  },
  {
    id: 28,
    category: 'education',
    titleTa: 'Student Study Content',
    titleEn: 'Student study content',
    descriptionTa: 'Exam tips, flashcards, Tamil learning carousels.',
    descriptionEn: 'Exam tips, flashcards, and Tamil learning carousels.',
    factTa: 'Students search செய்யும் words caption title-ல் இருந்தால் platform search-ல் better chance.',
    factEn: 'Use the exact words students search for in captions and titles for better platform search.',
    bestFor: ['Instagram', 'YouTube Shorts', 'Facebook'],
    tags: ['StudyTipsTamil', 'TamilEducation', 'ExamTips', 'StudentLife', 'LearnInTamil'],
  },
  {
    id: 29,
    category: 'creator',
    titleTa: 'Personal Branding',
    titleEn: 'Personal branding',
    descriptionTa: 'Founder, freelancer, creator authority posts.',
    descriptionEn: 'Founder, freelancer, and creator authority posts.',
    factTa: 'Personal brand post-ல் niche credibility caption-ல் தெரிந்தால் hashtags support signal ஆகும்.',
    factEn: 'When your niche credibility is clear in the caption, hashtags become a useful support signal.',
    bestFor: ['LinkedIn', 'Instagram', 'X'],
    tags: ['PersonalBranding', 'FounderJourney', 'TamilCreator', 'FreelancerLife', 'BuildInPublic'],
  },
  {
    id: 30,
    category: 'business',
    titleTa: 'SEO Blog & Website',
    titleEn: 'SEO blog and website',
    descriptionTa: 'Tamil blog posts, website tips, content marketing.',
    descriptionEn: 'Tamil blog posts, website tips, and content marketing.',
    factTa: 'Search traffic-க்கு hashtags இல்லை; keyword-rich title, internal links, useful content தான் முக்கியம்.',
    factEn: 'For search traffic, hashtags are not the driver; keyword-rich titles, internal links, and useful content matter more.',
    bestFor: ['LinkedIn', 'X', 'Facebook'],
    tags: ['SEOTips', 'TamilBlogging', 'ContentMarketing', 'WebsiteTips', 'DigitalMarketing'],
  },
];
